[41기 김승기] ADD : 카카오 소셜 로그인 기능 구현
wecode-bootcamp-korea/41-2nd-Air-GnG-backend pull request #4
Opened 2023-02-01 09:52 UTC by seuungkei

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
  - 카카오 api를 활용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 카카오로 로그인 시 데이터를 가져와 db에 있는지 확인 후 없을 시 db에 추가하는 로직을 구현하였습니다.

<br />

## :: 테스트 결과 이미지
<img width="255" alt="스크린샷 2023-02-01 오후 6 50 58" src="https://user-images.githubusercontent.com/111074566/216009529-64cd1844-5999-4e0c-80dd-aad23a1275e2.png">
<img width="962" alt="스크린샷 2023-02-01 오후 6 51 07" src="https://user-images.githubusercontent.com/111074566/216009545-00c694f3-6e86-4305-9c4d-2d27bd70aad5.png">
<img width="1413" alt="스크린샷 2023-02-01 오후 6 51 21" src="https://user-images.githubusercontent.com/111074566/216009573-b2d00be7-23fa-49d4-afe2-f787dff15a58.png">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-02 01:39 UTC, kyeongraekim requested changes

2023-02-02 01:39 UTC, kyeongraekim commented on api/services/userService.js
> +    const accessToken = jwt.sign({ userId: user.id }, process.env.SECRETKEY);
- .env file 내부 SECRET_KEY의 snake case를 변수명 네이밍 컨벤션에 맞게 설정해주세요!~

2023-02-02 01:39 UTC, kyeongraekim commented on api/services/userService.js
> +  const profileImage = kakaoUserInfo.data.properties.profile_image;
- 각각의 Property 데이터에 일일히 한 줄 한 줄 변수를 선언한 후 할당하는 것 보다 구조분해 할당을 이용하면 더 효율적으로 할당이 가능해지겠네요!

2023-02-02 01:39 UTC, kyeongraekim commented on api/routes/index.js
> +router.use('/users', userRouter.router);
- 인증 인가의 엔드포인트로는 "auth" 라는 표현이 자주 쓰이곤합니다. 엔드포인트와 확실히 구분되는 인증-인가의 목적을 지닌 auth로의 명칭으로 바꿔보는 것은 어떨까요?

2023-02-02 01:39 UTC, kyeongraekim commented on api/models/userDao.js
> +    );
- 이 부분은 kakaoId를 기준으로 user의 존재여부를 판단하는 Dao 함수로 보여지네요! SELECT EXIST 문으로 변형한 후, 얻어낸 0,1 의 불리언 값을 추후 서비스단에서 활용해 보는 것은 어떨까요?
- 위 기획으로 변경한다면 checkUserByKakaoId 정도로 변수명이 변경될 수 있겠네요! 
- 해당 내용은 추후에 getUserByxxx 에서 user의 모든 정보를 긁어오는 쿼리문과 차이가 있을 수 있겠네요!

2023-02-02 07:27 UTC, kyeongraekim requested changes

2023-02-02 07:27 UTC, kyeongraekim commented on api/services/userService.js
> +
- 이쪽 부분 properties 부분만 test code의 스타일처럼 수정해주시면 좋을 것 같습니다!~

2023-02-02 07:27 UTC, kyeongraekim commented on tests/user.test.js
> +    await request(app).post('/auth/login').set({ authorization: 'a' }).expect(400);
- authorization mock data를 보다 시인성있게 "mock_access_token" 등으로 바꾸어 주세요!

2023-02-02 07:27 UTC, kyeongraekim commented on api/services/userService.js
> +    const accessToken = jwt.sign({ userId: newUser.inserId }, process.env.JWT_SECRET_KEY);
- inserId의 t 부분이 빠져있는 것 같은데 혹시 잘 작동하던가요?

2023-02-03 06:19 UTC, sangwoong03 commented on api/controllers/userController.js
> +  if (!kakaoToken) detectError('NONE_ACCESS_TOKEN', 401);
해당 에러메시지는 인가 과정에서 accedToken이 없을 경우에 반환되는 에러메시지와 동일하여 혼란을 줄 수 있을 것 같습니다.
카카오 유저 정보를 받기 위해 토큰을 받지 못했다는 의미를 전달하는 것은 어떨까요?
```suggestion
  if (!kakaoToken) detectError('NONE_KAKAO_TOKEN', 401);
```

2023-02-03 06:19 UTC, sangwoong03 commented on api/services/userService.js
> +  }
카카오 공식문서에서 카카오 유저 정보를 조회했을 때 반드시 반환되는 값을 확인해야합니다.

예를 들어 nickname의 경우 유저가 닉네임을 설정하지 않았을 수도 있습니다. 프로필 이미지 정보도 없을 수도 있구요.

만약 유저 정보를 제대로 가져왔어도 다음과 같은 예외처리로 인해 로그인 로직이 제대로 이루어지지 않을 수 있습니다.

카카오 회원 정보를 조회했을 때 반환되는 데이터가 없을 경우 예외처리를 하는 것은 어떨까요?

2023-02-03 06:19 UTC, sangwoong03 commented on tests/user.test.js
> +    expect(response.body).toEqual({ message: 'NONE_ACCESS_TOKEN' });
controller 단에서 에러메시지 수정하면서 해당 부분도 수정해주세요!

2023-02-03 06:19 UTC, sangwoong03 commented on api/services/userService.js
> +  return accessToken;
두가지로 조회하는 방법도 좋아보입니다!

다만 두가지의 역할이 동일해보입니다.

kakaoId를 통해 유저를 조회하여 해당 유저가 있을 경우와 없는 경우의 두가지 분기처리를 한다면 코드를 좀 더 간결하게 작성할 수 있을 것 같습니다!

2023-02-03 07:28 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-03 07:28 UTC, merged