[41기 김승기] ADD : Hosting 시스템 기능 구현
wecode-bootcamp-korea/41-2nd-Air-GnG-backend pull request #8
Opened 2023-02-07 01:12 UTC by seuungkei

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- hosting 시스템에 대한 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 호스트에 대한 숙소 등록 시 host가 없으면 host에 먼저 등록 후 숙소 등록
- 내가 등록한 호스트에 예약이 있다면 자기가 등록 한 숙소에 예약 목록 보여주는 기능 구현

<br />

## :: 테스트 결과 이미지
<img width="906" alt="스크린샷 2023-02-07 오전 10 09 06" src="https://user-images.githubusercontent.com/111074566/217122693-a4706f19-11d7-477e-9038-71a194f851a8.png">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-07 08:31 UTC, kyeongraekim requested changes
전반적으로 깔끔하게 잘 작성해주셨네요!~ 아래 마이너한 내용들 수정 부탁드립니다!~

2023-02-07 08:31 UTC, kyeongraekim commented on api/controllers/hostingController.js
> +  const hostingRoom = await hostingService.getMyHostingList(req.userId);
- hostingService에서 받아오는 것이 list형태의 복수 데이터일 수 있으니 hostingRooms 정도의 변수명 설정이 더 의미론적으로 명확할 것 같아보입니다!~

2023-02-07 08:31 UTC, kyeongraekim commented on api/controllers/hostingController.js
> +  return res.status(200).json({ message: 'HOST_CREATE_COMPLETED!' });
- create 생성에 해당되는 상태코드에 맞게 201로 수정해주세요!~

2023-02-07 08:31 UTC, kyeongraekim commented on api/models/hostingDao.js
> +    for (let image = 0; image < 5; i++) {
- 해당 For문의 기능은 어떠한 의미를 담고있는지 아래 코멘트로 간략하게 작성해주세요!~

2023-02-07 08:31 UTC, kyeongraekim commented on api/models/hostingDao.js
> +    return;
- 이곳은 return 뒤에 아무것도 붙지 않는 것이 직접 의도한 내용이실까요? 한 번 판단해주시고 수정을 고려해주세요!~

2023-02-07 08:37 UTC, seuungkei commented on api/models/hostingDao.js
> +    for (let image = 0; image < 5; i++) {
호스트 숙소 등록 시 사진을 5개까지 등록이 가능하고 백엔드에는 배열인 형태로 데이터가 오게 되어서 for문을 통해 데이터를 넣는 형태로 구현을 하였습니다!

2023-02-07 09:48 UTC, kyeongraekim requested changes

2023-02-07 09:48 UTC, kyeongraekim commented on api/models/hostingDao.js
> +    for (let image = 0; image < 5; i++) {
- 그렇다면 해당 부분은 for 문이 한 번 돌 때마다 db를 히트하는 구조에서, 미리 만들어 놓은 형태를 한 번에 모두 집어넣는 bulk insert 하는 모습으로 진행되어야 마땅하겠네요!

2023-02-07 09:48 UTC, kyeongraekim commented on api/models/hostingDao.js
> +    for (let image = 0; image < 5; i++) {
- SQL 선에서의 bulk insert 내용으로 변경해보세요!

2023-02-07 13:38 UTC, seuungkei commented on api/models/hostingDao.js
> +    for (let image = 0; image < 5; i++) {
bulk insert 고려하여 수정하였습니다!

2023-02-08 01:11 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-08 01:12 UTC, merged